### ISSUE TITLE
more informativ warnings

### ISSUE THREAD

**Issue by kasparlund** [google/sentencepiece#264]
processing the english wikipedia i get thousands of the following warning : 
-LOG(WARNING) Empty string found. removed
-LOG(INFO) Too long lines (>=2048 bytes (it can be changed with --max_sentence_length flag). Skipped

Could we get these warnings in a more succinct information that doesn't float the terminal with info ?
Also I have no idea what "Empty string found" relates to

**Comment by taku910** [comment]
Thank you for the feedback.    I will make them appear only once.

**Comment by taku910** [comment]
Fixed the issue in the HEAD.

1. No error message is emitted when seeing empty string
2. Error of 'too-long-sentence' gets more informative and is emitted only once.

**Comment by kasparlund** [comment]
thanks

**Comment by rspeer** [comment]
I've pulled the master branch of sentencepiece, and run its build instructions. I still get an overwhelming number of lines of: `trainer_interface.cc(356) LOG(WARNING) Empty string found. removed`
