### ISSUE TITLE
: undefined symbol: _ZN10tensorflow12OpDefBuilder5InputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by fcqfcq** [google/sentencepiece#470]
#define EIGEN_USE_THREADS
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/op_kernel.h"

using namespace tensorflow;

class ZeroOutOp : public OpKernel {
 public:
  explicit ZeroOutOp(OpKernelConstruction* context) : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
    // Grab the input tensor
    const Tensor& input_tensor = context->input(0);
    auto input = input_tensor.flat<int32>();

    // Create an output tensor
    Tensor* output_tensor = NULL;
    OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(),
                                                     &output_tensor));
    auto output_flat = output_tensor->flat<int32>();

    // Set all but the first element of the output tensor to 0.
    const int N = input.size();
    for (int i = 1; i < N; i++) {
      output_flat(i) = 0;
    }

    // Preserve the first input value if possible.
    if (N > 0) output_flat(0) = input(0);
  }
};

// REGISTER_OP("ZeroOut")
//     .Input("to_zero: int32")
//     .Output("zeroed: int32")
//     .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
//       c->set_output(0, c->input(0));
//       return Status::OK();
//     });
REGISTER_OP("ZeroOut")
    .Input("to_zero: int32")
    .Output("zeroed: int32");    
REGISTER_KERNEL_BUILDER(Name("ZeroOut").Device(DEVICE_CPU), ZeroOutOp);

TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')
$TF_INC
$TF_LIB
g++ -std=c++11 -shared zero_out.cc -o zero_out.so -fPIC -I$TF_INC -I$TF_INC/external/nsync/public -L$TF_LIB -ltensorflow_framework -O2

**Comment by fcqfcq** [comment]
ubuntu 18  ,g++ 5.5, pip install  tensorflow=1.14.0

**Comment by fcqfcq** [comment]
Help me out in resolving this issue.
Thanks in advance.

**Comment by fcqfcq** [comment]
The same dynamic library can be run with a new machine

 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
conda  install tensorflow-gpu==1.14.0
g++-7.5

old  machine
5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
pip install tensorflow=1.14.0
g++-5.5  /g++-7.5


why?

**Comment by taku910** [comment]
Could you try tensorflow==1.15.0 and latest sentencepiece release?  I think this issue is fixed.
Please feel free to reopen it if you find the issue again,

**Comment by tsantosh1098** [comment]
> Could you try tensorflow==1.15.0 and latest sentencepiece release? I think this issue is fixed.
> Please feel free to reopen it if you find the issue again,

I also had similar problem, installing tensorflow-gpu==1.15.0 didn't solve my problem

**Comment by tsantosh1098** [comment]
Hello, I am working upsampling of point cloud using Ec-net https://github.com/yulequan/EC-Net to upsample the point cloud. now to run things parallel recent people have written cuda enabled kernals and tensorflow operators to use them under tensorflow... now there are 3 shared libraries getting generated in the project.

case 1: if I use tensorflow==1.14.0 the shared file gets generated but when I try to use that, I get following error tensorflow.python.framework.errors_impl.NotFoundError: code/tf_ops/emd/tf_auctionmatch_so.so: undefined symbol: _ZN10tensorflow12OpDefBuilder5InputENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

case 2: if I use tensorflow==1.15.0, i get /usr/bin/ld: cannot find -ltensorflow_framework

but when i go and check in /usr/local/lib/python3.6/dist-packages/tensorflow/ I get this following libtensorflow_framework.so@

but at the same time if I go and check for tf flags, import tensorflow as tf tf.sysconfig.get_link_flags()

['-L/usr/local/lib/python3.6/dist-packages/tensorflow_core',
'-l:libtensorflow_framework.so.1']

plz help me to solve this problem. thanks in advance
